export const POST_USER_PENDING = 'POST_USER_PENDING';
export const POST_USER_RESOLVED = 'POST_USER_RESOLVED';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';

export const GET_USER_BY_ID_RESOLVED = 'GET_USER_BY_ID_RESOLVED';
export const GET_USER_BY_ID_PENDING = 'GET_USER_BY_ID_PENDING';
export const GET_USER_BY_ID_REJECTED = 'GET_USER_BY_ID_REJECTED';

export const GET_USERS_BY_IDS_RESOLVED = 'GET_USERS_BY_IDS_RESOLVED';
export const GET_USERS_BY_IDS_PENDING = 'GET_USERS_BY_IDS_PENDING';
export const GET_USERS_BY_IDS_REJECTED = 'GET_USERS_BY_IDS_REJECTED';

export const DELETE_USER_RESOLVED = 'DELETE_USER_RESOLVED';
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';

export const SET_EVENTS_FINISHED = 'SET_EVENTS_FINISHED';
export const INCREMENT_EVENT_FINISH = 'INCREMENT_EVENT_FINISHED';

export const CREATE_EVENT_RESOLVED = 'CREATE_EVENT_RESOLVED';
export const CREATE_EVENT_REJECTED = 'CREATE_EVENT_REJECTED';

export const GET_EVENTS_RESOLVED = 'GET_EVENTS_RESOLVED';
export const GET_EVENTS_REJECTED = 'GET_EVENTS_REJECTED';

export const GET_EVENTS_BY_ID_RESOLVED = 'GET_EVENTS_BY_ID_RESOLVED';
export const GET_EVENTS_BY_ID_REJECTED = 'GET_EVENTS_BY_ID_REJECTED';

export const GET_EVENT_RESOLVED = 'GET_EVENT_RESOLVED';
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED';

export const UPDATE_EVENT_RESOLVED = 'UPDATE_EVENT_RESOLVED';
export const UPDATE_EVENT_REJECTED = 'UPDATE_EVENT_REJECTED';

export const DELETE_EVENT_RESOLVED = 'DELETE_EVENT_RESOLVED';
export const DELETE_EVENT_REJECTED = 'DELETE_EVENT_REJECTED';

export const GET_ATTENDEES_DETAILS_RESOLVED = 'GET_ATTENDEES_DETAILS_RESOLVED';
export const GET_ATTENDEES_DETAILS_REJECTED = 'GET_ATTENDEES_DETAILS_REJECTED';

export const GET_PROJECTS_RESOLVED = 'GET_PROJECTS_RESOLVED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';

export const DELETE_PROJECT_RESOLVED = 'DELETE_PROJECT_RESOLVED';
export const DELETE_PROJECT_REJECTED = 'DELETE_PROJECT_REJECTED';

export const GET_PROJECTS_BY_ORG_RESOLVED = 'GET_PROJECTS_BY_ORG_RESOLVED';
export const GET_PROJECTS_BY_ORG_REJECTED = 'GET_PROJECTS_BY_ORG_REJECTED';

export const GET_PROJECT_BY_ID_RESOLVED = 'GET_PROJECT_BY_ID_RESOLVED';
export const GET_PROJECT_BY_ID_PENDING = 'GET_PROJECT_BY_ID_PENDING';
export const GET_PROJECT_BY_ID_REJECTED = 'GET_PROJECT_BY_ID_REJECTED';

export const CREATE_PROJECT_RESOLVED = 'CREATE_PROJECT_RESOLVED';
export const CREATE_PROJECT_REJECTED = 'CREATE_PROJECT_REJECTED';
export const CREATE_PROJECT_PENDING = 'CREATE_PROJECT_PENDING';

export const UPDATE_PROJECT_RESOLVED = 'UPDATE_PROJECT_RESOLVED';
export const UPDATE_PROJECT_PENDING = 'UPDATE_PROJECT_PENDING';
export const UPDATE_PROJECT_REJECTED = 'UPDATE_PROJECT_REJECTED';

export const GET_ORGS_RESOLVED = 'GET_ORGS_RESOLVED';
export const GET_ORGS_REJECTED = 'GET_ORGS_REJECTED';
export const GET_ORGS_PENDING = 'GET_ORGS_PENDING';

export const GET_ORGS_BY_ID_RESOLVED = 'GET_ORGS_BY_ID_RESOLVED';
export const GET_ORGS_BY_ID_REJECTED = 'GET_ORGS_BY_ID_REJECTED';
export const GET_ORGS_BY_ID_PENDING = 'GET_ORGS_BY_ID_PENDING';

export const GET_ORG_BY_ID_RESOLVED = 'GET_ORG_BY_ID_RESOLVED';
export const GET_ORG_BY_ID_REJECTED = 'GET_ORG_BY_ID_REJECTED';
export const GET_ORG_BY_ID_PENDING = 'GET_ORG_BY_ID_PENDING';

export const CREATE_ORG_RESOLVED = 'CREATE_ORG_RESOLVED';
export const CREATE_ORG_REJECTED = 'CREATE_ORG_REJECTED';
export const CREATE_ORG_PENDING = 'CREATE_ORG_PENDING';

export const UPDATE_ORG_RESOLVED = 'UPDATE_ORG_RESOLVED';
export const UPDATE_ORG_REJECTED = 'UPDATE_ORG_REJECTED';
export const UPDATE_ORG_PENDING = 'UPDATE_ORG_PENDING';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_RESOLVED = 'LOGIN_USER_RESOLVED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const LOGOUT_USER = 'LOGOUT_USER';
