export const POST_USER_PENDING = 'POST_USER_PENDING';
export const POST_USER_RESOLVED = 'POST_USER_RESOLVED';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';

export const GET_USER_BY_ID_RESOLVED = 'GET_USER_BY_ID_RESOLVED';
export const GET_USER_BY_ID_PENDING = 'GET_USER_BY_ID_PENDING';
export const GET_USER_BY_ID_REJECTED = 'GET_USER_BY_ID_REJECTED';

export const SET_EVENTS_FINISHED = 'SET_EVENTS_FINISHED';
export const INCREMENT_EVENT_FINISH = 'INCREMENT_EVENT_FINISHED';

export const ADD_EVENT_RESOLVED = 'ADD_EVENT_RESOLVED';
export const ADD_EVENT_REJECTED = 'ADD_EVENT_REJECTED';

export const GET_EVENTS_RESOLVED = 'GET_EVENTS_RESOLVED';
export const GET_EVENTS_REJECTED = 'GET_EVENTS_REJECTED';

export const GET_EVENT_RESOLVED = 'GET_EVENT_RESOLVED';
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED';

export const DELETE_EVENT_RESOLVED = 'DELETE_EVENT_RESOLVED';
export const DELETE_EVENT_REJECTED = 'DELETE_EVENT_REJECTED';

export const GET_PROJECTS_RESOLVED = 'GET_PROJECTS_RESOLVED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';
export const DELETE_PROJECT_RESOLVED = 'DELETE_PROJECT_RESOLVED';
export const DELETE_PROJECT_REJECTED = 'DELETE_PROJECT_REJECTED';
export const GET_PROJECTS_BY_ORG_RESOLVED = 'GET_PROJECTS_BY_ORG_RESOLVED';
export const GET_PROJECTS_BY_ORG_REJECTED = 'GET_PROJECTS_BY_ORG_REJECTED';

export const GET_ORGANIZATIONS_RESOLVED = 'GET_ORGANIZATIONS_RESOLVED';
export const GET_ORGANIZATIONS_REJECTED = 'GET_ORGANIZATIONS_REJECTED';
export const GET_ORG_ID_RESOLVED = 'GET_ORG_ID_RESOLVED';
export const GET_ORG_ID_REJECTED = 'GET_ORG_ID_REJECTED';
export const ADD_ORG_RESOLVED = 'ADD_ORG_RESOLVED';
export const ADD_ORG_REJECTED = 'ADD_ORG_REJECTED';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_RESOLVED = 'LOGIN_USER_RESOLVED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const LOGOUT_USER = 'LOGOUT_USER';
